# Generated by Django 5.2.9 on 2026-01-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('cep', models.CharField(max_length=9)),
                ('numero', models.IntegerField()),
                ('compl', models.CharField(max_length=28)),
            ],
        ),
    ]
