# Generated by Django 5.2.9 on 2026-01-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='produtos/')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantidade', models.IntegerField(default=0)),
            ],
        ),
    ]
